name: "Gosec Security Checker"
description: "Runs the gosec security checker"
author: "@ccojocar"

inputs:
  args:
    description: "Arguments for gosec"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://ghcr.io/securego/gosec@sha256:2cf71ea78210c496c65e3a987576a9c8317b68e20f2960520b3f6f8f9f539be5" # 2.24.6
  args:
    - ${{ inputs.args }}

branding:
  icon: "shield"
  color: "blue"
